### PR TITLE
change x**2 by x*x, (a - c) back below the SQRT on lines 153-155, adiding one function to retrieve coeffs

### PR DESCRIPTION
**Pull request by djibb**
Hi, 
You will find a code that correct formulas as describe in paper on wolfram.com.

JBB
NB : this code was modified by one of my non-git users : Jean-François PITTET. A little word in merge message will be appreciate.

### CODE REVIEW

**Comment by djibb** [comment]
JF adds some condition in case of perfect circle. Then there's an issue with sign of coefficient.

**Comment by bdhammel** [comment]
These changes cause failing tests for me, can you please recheck the equations

**Comment by bdhammel** [comment]
> These changes cause failing tests for me, can you please recheck the equations

Nvm these were an issue with the tests

**Comment by bdhammel** [comment]
Thank you for these suggestions! they've been added to master

**Pull request closed without merging**
